<a href="https://colab.research.google.com/github/Hasifa1/Thyroid-cancer-prediction/blob/main/TD_feature_extraction_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from skimage import color, feature, io, transform
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [ ]:
# Set random seed for reproducibility
np.random.seed(42)

# Define paths to your image dataset for malign, benign, and normal cases
malignant_path = '/content/drive/MyDrive/dataset_thyroid/malign'
benign_path = '/content/drive/MyDrive/dataset_thyroid/benign'
normal_path = '/content/drive/MyDrive/dataset_thyroid/normal'

In [ ]:
# Define a function for feature extraction using HOG and LBP
def extract_features(image):
    # Convert the image to grayscale
    gray_image = color.rgb2gray(image)

    # Resize the image
    resized_image = transform.resize(gray_image, (224, 224))

    # Extract HOG features
    hog_features = feature.hog(resized_image, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), block_norm='L2-Hys')

    # Extract LBP features
    lbp_features = feature.local_binary_pattern(resized_image, P=8, R=1, method='uniform')

    # Flatten and concatenate the features
    flattened_features = np.concatenate((hog_features, lbp_features.ravel()))

    return flattened_features

In [ ]:
import os
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img_path = os.path.join(folder, filename)
        img = io.imread(img_path)
        if img is not None:
            images.append(img)
    return images

In [ ]:
# Extract features and create labels
malignant_images = load_images_from_folder(malignant_path)
benign_images = load_images_from_folder(benign_path)
normal_images = load_images_from_folder(normal_path)

In [ ]:

# Extract features and create labels
malignant_features = [extract_features(image) for image in malignant_images]
benign_features = [extract_features(image) for image in benign_images]
normal_features = [extract_features(image) for image in normal_images]

In [ ]:
# Concatenate features and labels
X = np.concatenate([malignant_features, benign_features, normal_features])
y = np.concatenate([np.ones(len(malignant_features)), np.ones(len(benign_features)) * 2, np.ones(len(normal_features)) * 3])

In [ ]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:

# Train an SVM classifier
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)


SVC()

In [ ]:

# Evaluate the classifier
svm_predictions = svm_classifier.predict(X_test)
accuracy = accuracy_score(y_test, svm_predictions)
print('accuracy: ',accuracy)
# Print classification report and confusion matrix
print(classification_report(y_test, svm_predictions))
print(confusion_matrix(y_test, svm_predictions))


accuracy:  0.6956521739130435
              precision    recall  f1-score   support

         1.0       0.65      0.97      0.78       180
         2.0       0.91      0.42      0.58       116
         3.0       0.00      0.00      0.00        26

    accuracy                           0.70       322
   macro avg       0.52      0.46      0.45       322
weighted avg       0.69      0.70      0.64       322

[[175   5   0]
 [ 67  49   0]
 [ 26   0   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
